<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog related posts template
 *
 * @var $block \Magefan\Blog\Block\Post\View\RelatedPosts
 */
?>

<?php if ($block->displayPosts()) { ?>
    <?php $_postCollection = $block->getPostCollection(); ?>
    <?php if ($_postCollection->count()) { ?>
    <div class="block related">
        <div class="block-title title">
            <strong id="block-relatedposts-heading" role="heading" aria-level="2">
                <?php echo __('Related Posts') ?>
            </strong>
        </div>
        <div class="block-content post-slider">
        <?php if ($_postCollection->count()) { ?>
            <div class="swiper-entry">
                <div class="swiper-container posts-slider carousel-area" data-breakpoints="1" data-xs-slides="1" data-sm-slides="2" data-md-slides="3" data-lt-slides="4" data-slides-per-view="4" data-autoheight="1" data-slides-per-group="1" data-speed="300">
                    <div class="swiper-wrapper">
            <?php foreach ($_postCollection as $_post) { ?>
            <?php
                $post_date = $_post->getData("publish_time");
            ?>
            <div class="swiper-slide">
                <div class="blog-post post-grid">
                    <?php
                        $post_date = $_post->getData("publish_time");
                    ?>
                    <?php if($post_image = $_post->getFeaturedImage()): ?>
                    <div class="post-image">
                        <img src="<?php echo $post_image; ?>" alt=""/>
                    </div>
                    <?php endif; ?>
                    <div class="post-detail">
                        <a class="post-item-link"
                           href="<?php echo $_post->getPostUrl() ?>">
                            <?php echo $block->escapeHtml($_post->getTitle()) ?>
                        </a>
                        <div class="meta-post">
                            <div class="entry-date published updated"><?php echo date("F", strtotime($post_date)); ?> <?php echo date("d", strtotime($post_date)); ?>, <?php echo date("Y", strtotime($post_date)); ?></div>
                        </div>
                    </div>
                </div>
            </div>               
            <?php } ?>
                    </div>
                </div>
                <div class="swiper-button-prev swiper-custom-left" tabindex="0" role="button" aria-label="Previous slide" aria-disabled="true"></div>
                <div class="swiper-button-next swiper-custom-right" tabindex="0" role="button" aria-label="Previous slide" aria-disabled="true"></div>
            </div>
            <script type="text/javascript">
                require([
                'jquery',
                'swiper',
                'swiper-skin',
                ], function ($, Swiper) {
                    Swiper_skin.init();
                });
            </script>
        <?php } ?>
        </div>
    </div>
    <?php } ?>
<?php } ?>