<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php
/** @var \Magento\ConfigurableProduct\Pricing\Render\FinalPriceBox$block */

// Daily deal Helper 
$helper=$this->helper('Redgiant\Dailydeals\Helper\Data');

$productId = $block->getSaleableItem()->getId();

/** @var \Magento\Framework\Pricing\Price\PriceInterface $priceModel */
$priceModel = $block->getPriceType('regular_price');

/** @var \Magento\Framework\Pricing\Price\PriceInterface $finalPriceModel */
$finalPriceModel = $block->getPriceType('final_price');
$idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';
if($this->getRequest()->getFullActionName() != 'catalog_product_view') {
    $idSuffix .= rtrim(base64_encode(md5(microtime())),"=");
}
$schema = ($block->getZone() == 'item_view') ? true : false;
?>
<?php if($helper->isDealProduct($productId) && $this->getRequest()->getFullActionName() != 'catalog_product_view') : ?>
    <?php
        $deal_final_price_amount = number_format($helper->getDealproductbyId($productId),2);
    ?>
    <span class="old-price">
        <?php /* @escapeNotVerified */ echo $block->renderAmount($finalPriceModel->getAmount(), [
            'display_label'     => __('Regular Price'),
            'price_id'          => $block->getPriceId('old-price-' . $idSuffix),
            'price_type'        => 'oldPrice',
            'include_container' => true,
            'skip_adjustments'  => true
        ]); ?>
    </span>
    <span class="special-price">
        <span class="price-container price-final_price tax weee">
            <span class="price-label">Special Price</span>
            <span id="product-price-<?php echo $idSuffix; ?>" data-price-amount="<?php echo $deal_final_price_amount; ?>" data-price-type="finalPrice" class="price-wrapper ">
                <span class="price"><?php echo $helper->getcurrencySymbol().''.$deal_final_price_amount; ?></span>
            </span>
        </span>
    </span>
<?php else: ?>
<span class="normal-price">
    <?php if($helper->isDealProduct($productId)): ?>
        <span class="old-price">
    <?php endif; ?>
    <?php
        $arguments = [
            'display_label' => __('As low as'),
            'price_id' => $block->getPriceId('product-price-' . $idSuffix),
            'price_type' => ($helper->isDealProduct($productId))?'old-price':'finalPrice',
            'include_container' => true,
            'schema' => $schema
        ];

        /* @noEscape */ echo $block->renderAmount($finalPriceModel->getAmount(), $arguments);
    ?>
    <?php if($helper->isDealProduct($productId)): ?>
        </span>
        <?php
            $deal_final_price_amount = number_format($helper->getDealproductbyId($productId),2);
        ?>
        <span class="special-price">
            <span class="price-container price-final_price tax weee">
                <span class="price-label">Special Price</span>
                <span id="product-price-<?php echo $idSuffix; ?>" data-price-type="special-price" data-price-amount="<?php echo $deal_final_price_amount; ?>" class="price-wrapper ">
                    <span class="price"><?php echo $helper->getcurrencySymbol().''.$deal_final_price_amount; ?></span>
                </span>
            </span>
        </span>
    <?php endif; ?>
</span>
<?php endif; ?>

<?php if (!$block->isProductList() && $block->hasSpecialPrice()): ?>
    <span class="old-price sly-old-price no-display">
        <?php /* @escapeNotVerified */ echo $block->renderAmount($priceModel->getAmount(), [
            'display_label'     => __('Regular Price'),
            'price_id'          => $block->getPriceId('old-price-' . $idSuffix),
            'price_type'        => 'oldPrice',
            'include_container' => true,
            'skip_adjustments'  => true
        ]); ?>
    </span>
<?php endif; ?>

<?php if ($block->showMinimalPrice()): ?>
    <?php if ($block->getUseLinkForAsLowAs()):?>
        <a href="<?= /* @escapeNotVerified */ $block->getSaleableItem()->getProductUrl() ?>" class="minimal-price-link">
            <?= /* @escapeNotVerified */ $block->renderAmountMinimal() ?>
        </a>
    <?php else:?>
        <span class="minimal-price-link">
            <?= /* @escapeNotVerified */ $block->renderAmountMinimal() ?>
        </span>
    <?php endif?>
<?php endif; ?>