<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog sidebar recent posts template
 *
 * @var $block \Magefan\Blog\Block\Sidebar\Recent
 */
?>

<?php
    $_postCollection = $block->getPostCollection();
?>
<?php if ($_postCollection->count()) { ?>
<div class="widget block block-recent-posts" data-bind="scope: 'recent-posts'">
    <div class="block-title">
        <strong><?php echo __('Recent Posts') ?></strong>
    </div>
    <div class="block-content">
        <?php foreach ($_postCollection as $_post) { ?>
            <div class="item">
                <?php
                    $post_date = $_post->getData("publish_time");
                ?>
                <?php if($post_image = $_post->getFeaturedImage()): ?>
                    <img src="<?php echo $post_image; ?>" alt=""/>
                <?php endif; ?>
                <div class="post-detail">
                    <a class="post-item-link"
                       href="<?php echo $_post->getPostUrl() ?>">
                        <?php echo $block->escapeHtml($_post->getTitle()) ?>
                    </a>
                    <div class="meta-post">
                        <div class="entry-date published updated"><?php echo date("F", strtotime($post_date)); ?> <?php echo date("d", strtotime($post_date)); ?>, <?php echo date("Y", strtotime($post_date)); ?></div>
                    </div>
                </div>
            </div>

        <?php } ?>
    </div>
</div>
<?php } ?>