<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog post list item template
 *
 * @var $block \Magefan\Blog\Block\Post\AbstractPost
 */
?>
<?php
    $_post = $this->getPost();
    $_postUrl = $_post->getPostUrl();
    $_postName = $block->escapeHtml($_post->getTitle(), null, true);
?>
<li class="post-holder post-holder-<?php echo $_post->getId() ?>">
    <?php 
        $scontent = $_post->getShortContent();
        $type = "";
        preg_match('/<div\s([^>]*\s)?data-type="(.*?)"(.*?)>/', $scontent, $out);

        if (!empty($out) && count($out) >= 3) {
            $type = "style".$out[2];
        }
    ?>
    <div class="post-header">
        <?php if (!$type && $featuredImage = $_post->getFeaturedImage()): ?>
        <div class="post-ftimg-hld">
            <a href="<?php echo $_postUrl ?>" title="<?php echo $_postName ?>">
                <img src="<?php echo $featuredImage ?>" alt="<?php echo $_postName ?>" />
            </a>
        </div>
        <?php endif; ?>
        <div class="post-title-holder clearfix">
            <h2 class="post-title">
                <a class="post-item-link"
                   href="<?php echo $_postUrl ?>">
                    <?php echo $_postName; ?>
                </a>
            </h2>

            <div class="addthis_toolbox addthis_default_style"
                addthis:url="<?php echo $_postUrl ?>"
                addthis:title="<?php echo $_postName; ?>"
                <?php if ($firstImage = $_post->getFirstImage()) { ?>
                addthis:media="<?php echo $firstImage ?>"
                <?php } ?>>
                <a class="addthis_button_facebook"></a>
                <a class="addthis_button_twitter"></a>
                <a class="addthis_button_email"></a>
                <a class="addthis_button_compact"></a>
            </div>
        </div>

        <?php echo $this->getInfoHtml() ?>
    </div>
    <?php if (!$type): ?>
    <div class="post-content">
        <div class="post-description clearfix">
            <div class="post-text-hld clearfix">
                <?php echo $block->getShorContent() ?>
            </div>
            <a href="javascript:void(0)" class="post-read-more limit-link h-icon-right"><span><?php echo __('Continue Reading') ?></span><i class="et-icon et-right-arrow"></i></a>
        </div>
    </div>
    <?php else: ?>
    <?php echo $block->getShorContent() ?>
    <div class="post-footer">
        <a href="javascript:void(0)" class="post-read-more limit-link h-icon-right"><span><?php echo __('Continue Reading') ?></span><i class="et-icon et-right-arrow"></i></a>
    </div>
    <?php endif; ?>
</li>