<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
$_helper = $this->helper('Redgiant\Xstore\Helper\Customtabs');
$xstore_helper = $this->helper('Redgiant\Xstore\Helper\Data');
?>
<?php if ($detailedInfoGroup = $block->getGroupChildNames('detailed_info', 'getChildHtml')):?>
    <div class="product info detailed">
        <?php $layout = $block->getLayout(); ?>
        <div class="product data items" data-mage-init='{"tabs":{"openedState":"active"}}'>
            <?php foreach ($detailedInfoGroup as $name):?>
                <?php
                    $html = $layout->renderElement($name);
                    if (!trim($html)) {
                        continue;
                    }
                    $alias = $layout->getElementAlias($name);
                    $label = $block->getChildData($alias, 'title');
                ?>
                <div class="data item title"
                     aria-labeledby="tab-label-<?= /* @escapeNotVerified */ $alias ?>-title"
                     data-role="collapsible" id="tab-label-<?= /* @escapeNotVerified */ $alias ?>">
                    <a class="data switch"
                       tabindex="-1"
                       data-toggle="switch"
                       href="#<?= /* @escapeNotVerified */ $alias ?>"
                       id="tab-label-<?= /* @escapeNotVerified */ $alias ?>-title">
                        <?= /* @escapeNotVerified */ $label ?>
                    </a>
                </div>
                <div class="data item content" id="<?= /* @escapeNotVerified */ $alias ?>" data-role="content">
                    <?= /* @escapeNotVerified */ $html ?>
                </div>
            <?php endforeach;?>
            <?php
                if($custom_cms_tabs = $_helper->getCustomTabs($xstore_helper->getCurrentProduct())) {
                    $i = 1;
                    foreach($custom_cms_tabs as $_item) {
                        ?>
                        <div class="data item title"
                             aria-labeledby="tab-label-<?php /* @escapeNotVerified */ echo "custom-".$i;?>-title"
                             data-role="collapsible" id="tab-label-<?php /* @escapeNotVerified */ echo "custom-".$i;?>">
                            <a class="data switch"
                               tabindex="-1"
                               data-toggle="switch"
                               href="#<?php /* @escapeNotVerified */ echo "custom-".$i; ?>"
                               id="tab-label-<?php /* @escapeNotVerified */ echo "custom-".$i;?>-title">
                                <span><?php /* @escapeNotVerified */ echo $_item['tab_title']; ?></span>
                            </a>
                        </div>
                        <div class="data item content" id="<?php /* @escapeNotVerified */ echo "custom-".$i; ?>" data-role="content">
                            <?php /* @escapeNotVerified */ echo $_item['tab_content']; ?>
                        </div>
                        <?php
                        $i++;
                    }
                }
            ?>
        </div>
    </div>
<?php endif; ?>
