<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product media data template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Gallery
 */
?>
<?php
$_helper = $this->helper('Redgiant\Xstore\Helper\Data');
$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');

$aspect_ratio = $_helper->getConfig("xstore_settings/product/enable_aspect_ratio");

if(empty($aspect_ratio)) {
    $aspect_ratio = 0;
}
$image_width = $_helper->getConfig("xstore_settings/product/image_width");
if(empty($image_width)) {
    $image_width = 700;
}
$image_height = $_helper->getConfig("xstore_settings/product/image_height");
if($aspect_ratio)
    $image_height = $image_width;
if(empty($image_height)) {
    $image_height = 700;
}

$_product_helper = $this->helper('Magento\Catalog\Helper\Data');
    
$product = $_product_helper->getProduct();

$product_page_type = $product->getData('xstore_product_page_layout');
if(!$product_page_type)
    $product_page_type = $_helper->getConfig('xstore_settings/product/product_page_layout');
if(empty($product_page_type))
    $product_page_type = 'default';
$current_page = $this->getRequest()->getFullActionName();
if($current_page == 'weltpixel_quickview_catalog_product_view')
    $product_page_type = 'default';

$navdir = 'horizontal';
if($product_page_type == 'vertical_gallery')
    $navdir = 'vertical';
?>
<?php if($product_page_type == 'fixed_content' || $product_page_type == 'center_fixed_image'): ?>
<?php
    $images = $product->getMediaGalleryImages();
?>
<div id="gallery_images">
    <?php
    if ($images instanceof \Magento\Framework\Data\Collection) {
        foreach ($images as $image) {
    ?>
    <div class="product-image-list">
        <?php if($aspect_ratio): ?>
        <img src="<?php echo $_imagehelper->init($product, 'product_page_image_medium')->setImageFile($image->getFile())->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize($image_width)->getUrl(); ?>" alt=""/>
        <?php else: ?>
        <img src="<?php echo $_imagehelper->init($product, 'product_page_image_medium')->setImageFile($image->getFile())->resize($image_width, $image_height)->getUrl(); ?>" alt=""/>
        <?php endif; ?>
    </div>
    <?php
        }
    }
    ?>
</div>
<script type="text/javascript">
require([
    'jquery'
], function ($) {
    var product_info_top = 0;
    var product_image_box_pos = $(".product.media").offset().top;

    $(window).scroll(function(){
        product_image_box_pos = $(".product.media").offset().top;
        if($(window).innerWidth() >= 992) {
            $(".product-info-main").each(function(){
                if(($(window).scrollTop() > product_image_box_pos - 50) && (product_image_box_pos + $(".product.media").outerHeight()) > ($(window).scrollTop() + $(this).outerHeight() + 50)) {
                    product_info_top = $(window).scrollTop() - product_image_box_pos + 50;
                    $(this).css('top',product_info_top + 'px');
                } else if ($(window).scrollTop() < product_image_box_pos || $(".product.media").outerHeight() < $(this).outerHeight()) {
                    product_info_top = 0;
                    $(this).css('top',product_info_top + 'px');
                } else {
                    product_info_top = $(".product.media").outerHeight() - $(this).outerHeight();
                    $(this).css('top',product_info_top + 'px');
                }
            });
        } else {
            product_info_top = 0;
            $(".product-info-main").css('top',product_info_top + 'px');
        }
    });

    $(window).resize(function(){
        product_image_box_pos = $(".product.media").offset().top;
        if($(window).innerWidth() >= 992) {
            $(".product-info-main").each(function(){
                if(($(window).scrollTop() > product_image_box_pos - 50) && (product_image_box_pos + $(".product.media").outerHeight()) > ($(window).scrollTop() + $(this).outerHeight() + 50)) {
                    product_info_top = $(window).scrollTop() - product_image_box_pos + 50;
                    $(this).css('top',product_info_top + 'px');
                } else if ($(window).scrollTop() < product_image_box_pos || $(".product.media").outerHeight() < $(this).outerHeight()) {
                    product_info_top = 0;
                    $(this).css('top',product_info_top + 'px');
                } else {
                    product_info_top = $(".product.media").outerHeight() - $(this).outerHeight();
                    $(this).css('top',product_info_top + 'px');
                }
            });
        } else {
            product_info_top = 0;
            $(".product-info-main").css('top',product_info_top + 'px');
        }
    });
});
</script>
<?php elseif($product_page_type == 'full_width_image'): ?>
<?php
    $images = $product->getMediaGalleryImages();
?>
<div class="stretch-swiper-slider">
    <div id="gallery_images" class="swiper-entry swipers-couple-wrapper images-wrapper arrows-hovered">
        <div class="swiper-container" data-slides-per-view="1" data-speed="300" data-space="0">
            <div class="swiper-wrapper">
                <?php
                if ($images instanceof \Magento\Framework\Data\Collection) {
                    foreach ($images as $image) {
                ?>
                <div class="swiper-slide text-center">
                    <?php if($aspect_ratio): ?>
                    <img src="<?php echo $_imagehelper->init($product, 'product_page_image_medium')->setImageFile($image->getFile())->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize($image_width)->getUrl(); ?>" alt=""/>
                    <?php else: ?>
                    <img src="<?php echo $_imagehelper->init($product, 'product_page_image_medium')->setImageFile($image->getFile())->resize($image_width, $image_height)->getUrl(); ?>" alt=""/>
                    <?php endif; ?>
                </div>
                <?php
                    }
                }
                ?>
            </div>
        </div>
        <div class="swiper-button-prev swiper-custom-left "></div>
        <div class="swiper-button-next swiper-custom-right "></div>

        <script type="text/javascript">
            require([
            'jquery',
            'swiper',
            'swiper-skin',
            ], function ($, Swiper) {
                Swiper_skin.init();
            });
        </script>
    </div>
</div>
<script type="text/javascript">
require([
    'jquery'
], function ($) {
    $(document).ready(function(){
        $(".product-info-container").append($(".product.info.detailed").detach());
    });
})
</script>
<?php else: ?>
<div class="gallery-placeholder _block-content-loading" data-gallery-role="gallery-placeholder">
    <div data-role="loader" class="loading-mask">
        <div class="loader">
            <img src="<?= /* @escapeNotVerified */ $block->getViewFileUrl('images/loader-1.gif') ?>"
                 alt="<?= /* @escapeNotVerified */ __('Loading...') ?>">
        </div>
    </div>
</div>
<!--Fix for jumping content. Loader must be the same size as gallery.-->
<script>
    var config = {
            "width": <?php /* @escapeNotVerified */ echo $image_width; ?>,
            "thumbheight": <?php /* @escapeNotVerified */ echo $block->getImageAttribute('product_page_image_small', 'height')
                        ?: $block->getImageAttribute('product_page_image_small', 'width'); ?>,
            "navtype": "<?= /* @escapeNotVerified */ $block->getVar("gallery/navtype") ?>",
            <?php if (!$aspect_ratio): ?>
                "height": <?php /* @escapeNotVerified */ echo $image_height; ?>
            <?php endif; ?>
        },
        thumbBarHeight = 0,
        loader = document.querySelectorAll('[data-gallery-role="gallery-placeholder"] [data-role="loader"]')[0];

    if (config.navtype === 'horizontal') {
        thumbBarHeight = config.thumbheight;
    }

    loader.style.paddingBottom = ( config.height / config.width * 100) + "%";
</script>
<script type="text/x-magento-init">
    {
        "[data-gallery-role=gallery-placeholder]": {
            "mage/gallery/gallery": {
                "mixins":["magnifier/magnify"],
                "magnifierOpts": <?= /* @escapeNotVerified */ $block->getMagnifier() ?>,
                "data": <?= /* @escapeNotVerified */ $block->getGalleryImagesJson() ?>,
                "options": {
                    "nav": "<?= /* @escapeNotVerified */ $block->getVar("gallery/nav") ?>",
                    <?php if (($block->getVar("gallery/loop"))): ?>
                        "loop": <?= /* @escapeNotVerified */ $block->getVar("gallery/loop") ?>,
                    <?php endif; ?>
                    <?php if (($block->getVar("gallery/keyboard"))): ?>
                        "keyboard": <?= /* @escapeNotVerified */ $block->getVar("gallery/keyboard") ?>,
                    <?php endif; ?>
                    <?php if (($block->getVar("gallery/arrows"))): ?>
                        "arrows": <?= /* @escapeNotVerified */ $block->getVar("gallery/arrows") ?>,
                    <?php endif; ?>
                    <?php if (($block->getVar("gallery/allowfullscreen"))): ?>
                        "allowfullscreen": <?= /* @escapeNotVerified */ $block->getVar("gallery/allowfullscreen") ?>,
                    <?php endif; ?>
                    <?php if (($block->getVar("gallery/caption"))): ?>
                        "showCaption": <?= /* @escapeNotVerified */ $block->getVar("gallery/caption") ?>,
                    <?php endif; ?>
                    "width": <?php /* @escapeNotVerified */ echo $image_width; ?>,
                    "thumbwidth": "<?= /* @escapeNotVerified */ $block->getImageAttribute('product_page_image_small', 'width') ?>",
                    <?php if ($block->getImageAttribute('product_page_image_small', 'height') || $block->getImageAttribute('product_page_image_small', 'width')): ?>
                        "thumbheight": <?php /* @escapeNotVerified */ echo $block->getImageAttribute('product_page_image_small', 'height')
                        ?: $block->getImageAttribute('product_page_image_small', 'width'); ?>,
                    <?php endif; ?>
                    <?php if (($block->getVar("gallery/thumbmargin"))): ?>
                        "thumbmargin": <?= /* @noEscape */ (int)$block->getVar("gallery/thumbmargin"); ?>,
                    <?php endif; ?>
                    <?php if (!$aspect_ratio): ?>
                        "height": <?php /* @escapeNotVerified */ echo $image_height; ?>,
                    <?php endif; ?>
                    <?php if ($block->getVar("gallery/transition/duration")): ?>
                        "transitionduration": <?= /* @escapeNotVerified */ $block->getVar("gallery/transition/duration") ?>,
                    <?php endif; ?>
                    "transition": "<?= /* @escapeNotVerified */ $block->getVar("gallery/transition/effect") ?>",
                    <?php if (($block->getVar("gallery/navarrows"))): ?>
                        "navarrows": <?= /* @escapeNotVerified */ $block->getVar("gallery/navarrows") ?>,
                    <?php endif; ?>
                    "navtype": "<?= /* @escapeNotVerified */ $block->getVar("gallery/navtype") ?>",
                    "navdir": "<?= /* @escapeNotVerified */ $navdir ?>"
                },
                "fullscreen": {
                    "nav": "<?= /* @escapeNotVerified */ $block->getVar("gallery/fullscreen/nav") ?>",
                    <?php if ($block->getVar("gallery/fullscreen/loop")): ?>
                        "loop": <?= /* @escapeNotVerified */ $block->getVar("gallery/fullscreen/loop") ?>,
                    <?php endif; ?>
                    "navdir": "<?= /* @escapeNotVerified */ $block->getVar("gallery/fullscreen/navdir") ?>",
                    <?php if ($block->getVar("gallery/transition/navarrows")): ?>
                        "navarrows": <?= /* @escapeNotVerified */ $block->getVar("gallery/fullscreen/navarrows") ?>,
                    <?php endif; ?>
                    "navtype": "<?= /* @escapeNotVerified */ $block->getVar("gallery/fullscreen/navtype") ?>",
                    <?php if ($block->getVar("gallery/fullscreen/arrows")): ?>
                        "arrows": <?= /* @escapeNotVerified */ $block->getVar("gallery/fullscreen/arrows") ?>,
                    <?php endif; ?>
                    <?php if ($block->getVar("gallery/fullscreen/caption")): ?>
                        "showCaption": <?= /* @escapeNotVerified */ $block->getVar("gallery/fullscreen/caption") ?>,
                    <?php endif; ?>
                    <?php if ($block->getVar("gallery/fullscreen/transition/duration")): ?>
                        "transitionduration": <?= /* @escapeNotVerified */ $block->getVar("gallery/fullscreen/transition/duration") ?>,
                    <?php endif; ?>
                    "transition": "<?= /* @escapeNotVerified */ $block->getVar("gallery/fullscreen/transition/effect") ?>"
                },
                "breakpoints": <?= /* @escapeNotVerified */ $block->getBreakpoints() ?>
            }
        }
    }
</script>
    <?php if($product_page_type == 'fixed_content_fotorama'): ?>
        <script type="text/javascript">
        require([
            'jquery'
        ], function ($) {
            var product_info_top = 0;
            var product_image_box_pos = $(".product.media").offset().top;

            $(window).scroll(function(){
                product_image_box_pos = $(".product.media").offset().top;
                if($(window).innerWidth() >= 992) {
                    $(".product-info-main").each(function(){
                        if(($(window).scrollTop() > product_image_box_pos - 1) && (product_image_box_pos + $(".product.media").outerHeight()) > ($(window).scrollTop() + $(this).outerHeight() + 1)) {
                            product_info_top = $(window).scrollTop() - product_image_box_pos + 1;
                            $(this).css('top',product_info_top + 'px');
                        } else if ($(window).scrollTop() < product_image_box_pos || $(".product.media").outerHeight() < $(this).outerHeight()) {
                            product_info_top = 0;
                            $(this).css('top',product_info_top + 'px');
                        } else {
                            product_info_top = $(".product.media").outerHeight() - $(this).outerHeight();
                            $(this).css('top',product_info_top + 'px');
                        }
                    });
                } else {
                    product_info_top = 0;
                    $(".product-info-main").css('top',product_info_top + 'px');
                }
            });

            $(window).resize(function(){
                product_image_box_pos = $(".product.media").offset().top;
                if($(window).innerWidth() >= 992) {
                    $(".product-info-main").each(function(){
                        if(($(window).scrollTop() > product_image_box_pos - 1) && (product_image_box_pos + $(".product.media").outerHeight()) > ($(window).scrollTop() + $(this).outerHeight() + 1)) {
                            product_info_top = $(window).scrollTop() - product_image_box_pos + 1;
                            $(this).css('top',product_info_top + 'px');
                        } else if ($(window).scrollTop() < product_image_box_pos || $(".product.media").outerHeight() < $(this).outerHeight()) {
                            product_info_top = 0;
                            $(this).css('top',product_info_top + 'px');
                        } else {
                            product_info_top = $(".product.media").outerHeight() - $(this).outerHeight();
                            $(this).css('top',product_info_top + 'px');
                        }
                    });
                } else {
                    product_info_top = 0;
                    $(".product-info-main").css('top',product_info_top + 'px');
                }
            });
        });
        </script>
    <?php endif; ?>
<?php endif; ?>